#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TravelingApp.Resource", IsApplication=true)]

namespace TravelingApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int firstCurrency = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonsigninstyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int emailIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int emailIcon2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_overflow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int xs = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int btnDialogEmail = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int btnDialogSignIn = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int btnSignUp = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int btnSignin = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int content_fragment = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int item_subtitle = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int item_title = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int menu = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int progressBar1 = 2131296268;
			
			// aapt resource value: 0x7f090010
			public const int sample_content_fragment = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int sample_main_layout = 2131296271;
			
			// aapt resource value: 0x7f090005
			public const int sliding_tabs = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int txtCreateAccount = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int txtEmail = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int txtOr = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int txtPassword = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int txtUserName = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int viewpager = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_in = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_sign_up = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_sample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int pager_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScrollMain = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar_main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int firstSpinner = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
